name: Runs tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  runtests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install tox tox-gh-actions
    - name: Run tests
      run: |
        tox
